[package]
name = "rusticnes-cli"
version = "0.1.0"
authors = ["Nicholas Flynt <thegamefreak0134@gmail.com>"]

[dependencies]
image = "*"
rusticnes-core = { git = "https://github.com/zeta0134/rusticnes-core" }